apiVersion: apps/v1
kind: Deployment
metadata:
  name: nameisoef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nameisoef
  template:
    metadata:
      labels:
        app: nameisoef
    spec:
      containers:
      - image: okteto.dev/nameisoef:latest
        name: nameisoef
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2bb7ba08-e62a-4f02-a778-634f0d1d6bae"
        - name: Vless_Path
          value: "/vl23dswer"
        - name: Vmess_UUID
          value: "2bb7ba08-e62a-4f02-a778-634f0d1d6bae"
        - name: Vmess_Path
          value: "/vm224swr"
        - name: Share_Path
          value: "/v2link"
